development:
  adapter: postgresql
  encoding: unicode
  database: plastmuse_development
  host: localhost
  pool: 5
  timeout: 5000
  username: <%= ENV["POSTGRESQL_PLASTMUSE_ADMIN"] %>
  password: <%= ENV["POSTGRESQL_PLASTMUSE_ADMIN_PASSWORD"] %>


test:
  adapter: postgresql
  encoding: unicode
  database: plastmuse_test
  host: localhost
  pool: 5
  timeout: 5000
  username: <%= ENV["POSTGRESQL_PLASTMUSE_ADMIN"] %>
  password: <%= ENV["POSTGRESQL_PLASTMUSE_ADMIN_PASSWORD"] %>


production:
  adapter: postgresql
  encoding: unicode
  database: plastmuse_production
  host: localhost
  pool: 5
  timeout: 5000
  username: <%= ENV["POSTGRESQL_PLASTMUSE_ADMIN"] %>
  password: <%= ENV["POSTGRESQL_PLASTMUSE_ADMIN_PASSWORD"] %>
