require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::BiographiesController do
 let!(:user) { FactoryGirl.create(:user) }
  before(:each) do
    sign_in(user)
  end

  # This should return the minimal set of attributes required to create a valid
  # Biography. As you add validations to Biography, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BiographiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all biographies as @biographies" do
      biography = Biography.create! valid_attributes
      get :index, {}, valid_session
      assigns(:biographies).should eq([biography])
    end
  end

  describe "GET show" do
    it "assigns the requested biography as @biography" do
      biography = Biography.create! valid_attributes
      get :show, {:id => biography.to_param}, valid_session
      assigns(:biography).should eq(biography)
    end
  end

  describe "GET new" do
    it "assigns a new biography as @biography" do
      get :new, {}, valid_session
      assigns(:biography).should be_a_new(Biography)
    end
  end

  describe "GET edit" do
    it "assigns the requested biography as @biography" do
      biography = Biography.create! valid_attributes
      get :edit, {:id => biography.to_param}, valid_session
      assigns(:biography).should eq(biography)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Biography" do
        expect {
          post :create, {:biography => valid_attributes}, valid_session
        }.to change(Biography, :count).by(1)
      end

      it "assigns a newly created biography as @biography" do
        post :create, {:biography => valid_attributes}, valid_session
        assigns(:biography).should be_a(Biography)
        assigns(:biography).should be_persisted
      end

      it "redirects to the created biography" do
        post :create, {:biography => valid_attributes}, valid_session
        response.should redirect_to([:admin, Biography.last])
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved biography as @biography" do
        # Trigger the behavior that occurs when invalid params are submitted
        Biography.any_instance.stub(:save).and_return(false)
        post :create, {:biography => { "name" => "invalid value" }}, valid_session
        assigns(:biography).should be_a_new(Biography)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Biography.any_instance.stub(:save).and_return(false)
        post :create, {:biography => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested biography" do
        biography = Biography.create! valid_attributes
        # Assuming there are no other biographies in the database, this
        # specifies that the Biography created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Biography.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => biography.to_param, :biography => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested biography as @biography" do
        biography = Biography.create! valid_attributes
        put :update, {:id => biography.to_param, :biography => valid_attributes}, valid_session
        assigns(:biography).should eq(biography)
      end

      it "redirects to the biography" do
        biography = Biography.create! valid_attributes
        put :update, {:id => biography.to_param, :biography => valid_attributes}, valid_session
        response.should redirect_to([:admin, biography])
      end
    end

    describe "with invalid params" do
      it "assigns the biography as @biography" do
        biography = Biography.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Biography.any_instance.stub(:save).and_return(false)
        put :update, {:id => biography.to_param, :biography => { "name" => "invalid value" }}, valid_session
        assigns(:biography).should eq(biography)
      end

      it "re-renders the 'edit' template" do
        biography = Biography.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Biography.any_instance.stub(:save).and_return(false)
        put :update, {:id => biography.to_param, :biography => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested biography" do
      biography = Biography.create! valid_attributes
      expect {
        delete :destroy, {:id => biography.to_param}, valid_session
      }.to change(Biography, :count).by(-1)
    end

    it "redirects to the biographies list" do
      biography = Biography.create! valid_attributes
      delete :destroy, {:id => biography.to_param}, valid_session
      response.should redirect_to(admin_biographies_url)
    end
  end

end
