require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExhibitionsController do

  # This should return the minimal set of attributes required to create a valid
  # Exhibition. As you add validations to Exhibition, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExhibitionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all exhibitions as @exhibitions" do
      exhibition = Exhibition.create! valid_attributes
      get :index, {}, valid_session
      assigns(:exhibitions).should eq([exhibition])
    end
  end

  describe "GET show" do
    it "assigns the requested exhibition as @exhibition" do
      exhibition = Exhibition.create! valid_attributes
      get :show, {:id => exhibition.to_param}, valid_session
      assigns(:exhibition).should eq(exhibition)
    end
  end

  describe "GET new" do
    it "assigns a new exhibition as @exhibition" do
      get :new, {}, valid_session
      assigns(:exhibition).should be_a_new(Exhibition)
    end
  end

  describe "GET edit" do
    it "assigns the requested exhibition as @exhibition" do
      exhibition = Exhibition.create! valid_attributes
      get :edit, {:id => exhibition.to_param}, valid_session
      assigns(:exhibition).should eq(exhibition)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Exhibition" do
        expect {
          post :create, {:exhibition => valid_attributes}, valid_session
        }.to change(Exhibition, :count).by(1)
      end

      it "assigns a newly created exhibition as @exhibition" do
        post :create, {:exhibition => valid_attributes}, valid_session
        assigns(:exhibition).should be_a(Exhibition)
        assigns(:exhibition).should be_persisted
      end

      it "redirects to the created exhibition" do
        post :create, exhibition: FactoryGirl.attributes_for(:exhibition)
        response.should redirect_to(Exhibition.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved exhibition as @exhibition" do
        # Trigger the behavior that occurs when invalid params are submitted
        Exhibition.any_instance.stub(:save).and_return(false)
        post :create, {:exhibition => { "name" => "invalid value" }}, valid_session
        assigns(:exhibition).should be_a_new(Exhibition)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Exhibition.any_instance.stub(:save).and_return(false)
        post :create, {:exhibition => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested exhibition" do
        exhibition = Exhibition.create! valid_attributes
        # Assuming there are no other exhibitions in the database, this
        # specifies that the Exhibition created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Exhibition.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => exhibition.to_param, :exhibition => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested exhibition as @exhibition" do
        exhibition = Exhibition.create! valid_attributes
        put :update, {:id => exhibition.to_param, :exhibition => valid_attributes}, valid_session
        assigns(:exhibition).should eq(exhibition)
      end

      it "redirects to the exhibition" do
        exhibition = Exhibition.create! valid_attributes
        put :update, {:id => exhibition.to_param, :exhibition => valid_attributes}, valid_session
        response.should redirect_to(exhibition)
      end
    end

    describe "with invalid params" do
      it "assigns the exhibition as @exhibition" do
        exhibition = Exhibition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Exhibition.any_instance.stub(:save).and_return(false)
        put :update, {:id => exhibition.to_param, :exhibition => { "name" => "invalid value" }}, valid_session
        assigns(:exhibition).should eq(exhibition)
      end

      it "re-renders the 'edit' template" do
        exhibition = Exhibition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Exhibition.any_instance.stub(:save).and_return(false)
        put :update, {:id => exhibition.to_param, :exhibition => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested exhibition" do
      exhibition = Exhibition.create! valid_attributes
      expect {
        delete :destroy, {:id => exhibition.to_param}, valid_session
      }.to change(Exhibition, :count).by(-1)
    end

    it "redirects to the exhibitions list" do
      exhibition = Exhibition.create! valid_attributes
      delete :destroy, {:id => exhibition.to_param}, valid_session
      response.should redirect_to(exhibitions_url)
    end
  end

end
